version: "3"
services:
  scraper:
    image: scraper-app:final
    ports:
      - "5001:5001"           # main app uses default port

  app:
    depends_on:
      - scraper
    image: app:final
    ports:
      - "5000:5000"           # default flask port

  update:
    depends_on:
      - scraper
      - app
    image: update:final
