version: "3"
services:
  scraper:
    build:
      context: ./scraper_app
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  app:
    depends_on:
      - scraper
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  update:
    depends_on:
      - scraper
      - app
    build:
      context: ./app/models
      dockerfile: Dockerfile
